services:
  preprocess:
    build:
      context: ./preprocess
    volumes:
      - ./data:/data
    command: python handler.py

  train:
    build:
      context: ./train
    volumes:
      - ./data:/data
    depends_on:
      - preprocess
    command: python handler.py

  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web/database:/data/database
      - ./data/models:/data/models
      - ./data/encoders:/data/encoders
      - ./data/raw:/data/raw
      - ./data/processed:/data/processed
    depends_on:
      - train
